# Generated by Django 3.1.1 on 2020-09-29 14:52

from django.db import migrations, models
import django.db.models.deletion
import pesticide_app.models.issue_status


class Migration(migrations.Migration):

    dependencies = [
        ('pesticide_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.ForeignKey(default=pesticide_app.models.issue_status.IssueStatus.get_default_issue_status, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pesticide_app.issuestatus'),
        ),
    ]
