# Generated by Django 3.1.1 on 2020-10-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesticide_app', '0002_auto_20200929_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='title',
            field=models.CharField(max_length=127),
        ),
    ]
