# Generated by Django 3.1.1 on 2021-01-01 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pesticide_app', '0003_auto_20201011_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emoticon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=35)),
                ('aria_label', models.CharField(blank=True, max_length=35)),
                ('search_keywords', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='pesticide_app.comment')),
                ('emoticon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emoticon_reaction', to='pesticide_app.emoticon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_reacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'emoticon', 'comment')},
            },
        ),
    ]
