# Generated by Django 3.1.1 on 2021-01-01 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pesticide_app', '0004_emoticon_reactor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reactor',
            options={'ordering': ['-emoticon']},
        ),
    ]
