# Generated by Django 3.1.1 on 2021-01-01 21:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesticide_app', '0005_auto_20210102_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactor',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
