# Generated by Django 3.1.1 on 2021-01-01 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pesticide_app', '0009_auto_20210102_0330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reactor',
            options={'ordering': ['emoticon', 'comment', '-timestamp']},
        ),
    ]
