# Generated by Django 3.1.1 on 2022-02-18 12:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pesticide_app', '0011_auto_20210105_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('repository_name', models.CharField(max_length=500)),
                ('ssh_url', models.CharField(max_length=1000)),
                ('path', models.CharField(max_length=1000)),
                ('secret', models.CharField(max_length=1000)),
                ('branch', models.CharField(max_length=1000)),
                ('identifier', models.CharField(max_length=100, unique=True)),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhook_creator', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='pesticide_app.project')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
