# Generated by Django 3.1.1 on 2022-01-28 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pesticide_app', '0012_webhookdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webhookdetails',
            old_name='identifer',
            new_name='identifier',
        ),
    ]
