# Generated by Django 3.1.1 on 2022-01-28 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pesticide_app', '0013_auto_20220128_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webhookdetails',
            name='project_name',
        ),
        migrations.AddField(
            model_name='webhookdetails',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pesticide_app.project'),
            preserve_default=False,
        ),
    ]
