# Generated by Django 3.1.1 on 2022-01-30 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pesticide_app', '0014_auto_20220128_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookdetails',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='pesticide_app.project'),
        ),
    ]
