version: "3.2"
services:
  redis:
    restart: always
    image: redis:5
    ports:
      - "6379:6379"
    networks:
      - db-net

  db:
    restart: always
    image: mysql:5.7
    environment:
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=pesticide_docker
      - MYSQL_USER=test_user
      - MYSQL_PASSWORD=test_user_password
      - MYSQL_ROOT_PASSWORD=ROOT_PASSWORD
    ports:
      - "3302:3306"
    networks:
      - db-net

  backend:
    restart: always
    container_name: pesticide_backend
    command: bash -c "cd ./src && python check_db.py --service-name db --ip db --port 3306 && python manage.py collectstatic --noinput && python manage.py makemigrations pesticide_app && python manage.py makemigrations && python manage.py migrate && daphne -b 0.0.0.0 -p 8000 pesticide.asgi:application"
    build:
      context: ./pesticide_backend/
      dockerfile: Dockerfile
    volumes:
      - ./pesticide_backend:/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    networks:
      - db-net

  frontend:
    command: npm run build
    container_name: pesticide_frontend
    build:
      context: ./pesticide_frontend/
      dockerfile: Dockerfile
    volumes:
      - ./pesticide_frontend:/frontend
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - backend
    networks:
      - db-net

  nginx:
    restart: always
    image: nginx:latest
    ports:
      - 7765:8080
    volumes:
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - ./pesticide_frontend/build:/var/www/frontend
      - ./pesticide_backend/src/media:/backend/src/media
      - ./pesticide_backend/src/backend-static:/backend/src/backend-static
    depends_on:
      - backend
    networks:
      - db-net

networks:
  db-net:
    driver: bridge
