const emoticons = [
  { expression: "thumbs_up", emoji: "👍" },
  { expression: "thumbs_down", emoji: "👎" },
  { expression: "correct", emoji: "✅" },
  { expression: "wrong", emoji: "❌" },
  { expression: "happy_face", emoji: "😀" },
  { expression: "laughing_face", emoji: "😂" },
  { expression: "wink_face", emoji: "😉" },
  { expression: "face_with_sunglasses", emoji: "😎" },
  { expression: "sad_face", emoji: "😔" },
  { expression: "crying_face", emoji: "😭" },
  { expression: "angry_face", emoji: "😠" },
  { expression: "sweat_face", emoji: "😅" },
  { expression: "hugging_face", emoji: "🤗" },
  { expression: "brain_exploding_face", emoji: "🤯" },
  { expression: "love", emoji: "❤️" },
  { expression: "eyes", emoji: "👀" },
  { expression: "hooray", emoji: "🎉" },
  { expression: "fire", emoji: "🔥" },
  { expression: "rocket", emoji: "🚀" },
  { expression: "brain", emoji: "🧠" },
  { expression: "sparkles", emoji: "✨" },
  { expression: "hundred", emoji: "💯" },
  { expression: "fingers_crossed", emoji: "🤞" },
  { expression: "question_mark", emoji: "❓" },
  { expression: "poop", emoji: "💩" },
  { expression: "clown", emoji: "🤡" },
]

export default emoticons